// --- データ定義 (全300単語) ---
// Rarity 1: Common (50%)
// Rarity 2: Rare (30%)
// Rarity 3: Super Rare (15%)
// Rarity 4: Ultra Rare (5%)

const VOCABULARY = [
    // --- Common (★1) Everyday Items & Basics ---
    { id: 'apple', word: 'Apple', jp: 'りんご', icon: '🍎', rarity: 1, bg: 'bg-red-50' },
    { id: 'banana', word: 'Banana', jp: 'バナナ', icon: '🍌', rarity: 1, bg: 'bg-yellow-50' },
    { id: 'orange', word: 'Orange', jp: 'みかん', icon: '🍊', rarity: 1, bg: 'bg-orange-50' },
    { id: 'cat', word: 'Cat', jp: 'ねこ', icon: '🐱', rarity: 1, bg: 'bg-orange-50' },
    { id: 'dog', word: 'Dog', jp: 'いぬ', icon: '🐶', rarity: 1, bg: 'bg-amber-50' },
    { id: 'pig', word: 'Pig', jp: 'ぶた', icon: '🐷', rarity: 1, bg: 'bg-pink-50' },
    { id: 'cow', word: 'Cow', jp: 'うし', icon: '🐮', rarity: 1, bg: 'bg-stone-50' },
    { id: 'mouse', word: 'Mouse', jp: 'ねずみ', icon: '🐭', rarity: 1, bg: 'bg-stone-100' },
    { id: 'egg', word: 'Egg', jp: 'たまご', icon: '🥚', rarity: 1, bg: 'bg-yellow-50' },
    { id: 'milk', word: 'Milk', jp: 'ぎゅうにゅう', icon: '🥛', rarity: 1, bg: 'bg-blue-50' },
    { id: 'bread', word: 'Bread', jp: 'パン', icon: '🍞', rarity: 1, bg: 'bg-orange-50' },
    { id: 'rice', word: 'Rice', jp: 'ごはん', icon: '🍚', rarity: 1, bg: 'bg-white' },
    { id: 'ball', word: 'Ball', jp: 'ボール', icon: '⚽', rarity: 1, bg: 'bg-stone-50' },
    { id: 'book', word: 'Book', jp: 'ほん', icon: '📚', rarity: 1, bg: 'bg-blue-50' },
    { id: 'pen', word: 'Pen', jp: 'ペン', icon: '🖊️', rarity: 1, bg: 'bg-slate-50' },
    { id: 'pencil', word: 'Pencil', jp: 'えんぴつ', icon: '✏️', rarity: 1, bg: 'bg-yellow-50' },
    { id: 'eraser', word: 'Eraser', jp: 'けしゴム', icon: '🧼', rarity: 1, bg: 'bg-white' },
    { id: 'ruler', word: 'Ruler', jp: 'じょうぎ', icon: '📏', rarity: 1, bg: 'bg-yellow-50' },
    { id: 'shirt', word: 'Shirt', jp: 'シャツ', icon: '👕', rarity: 1, bg: 'bg-cyan-50' },
    { id: 'shoes', word: 'Shoes', jp: 'くつ', icon: '👟', rarity: 1, bg: 'bg-red-50' },
    { id: 'socks', word: 'Socks', jp: 'くつした', icon: '🧦', rarity: 1, bg: 'bg-green-50' },
    { id: 'hat', word: 'Hat', jp: 'ぼうし', icon: '🧢', rarity: 1, bg: 'bg-blue-100' },
    { id: 'car', word: 'Car', jp: 'くるま', icon: '🚗', rarity: 1, bg: 'bg-red-100' },
    { id: 'bus', word: 'Bus', jp: 'バス', icon: '🚌', rarity: 1, bg: 'bg-yellow-100' },
    { id: 'taxi', word: 'Taxi', jp: 'タクシー', icon: '🚕', rarity: 1, bg: 'bg-yellow-50' },
    { id: 'flower', word: 'Flower', jp: 'おはな', icon: '🌷', rarity: 1, bg: 'bg-pink-50' },
    { id: 'tree', word: 'Tree', jp: 'き', icon: '🌳', rarity: 1, bg: 'bg-green-100' },
    { id: 'sun', word: 'Sun', jp: 'たいよう', icon: '☀️', rarity: 1, bg: 'bg-orange-100' },
    { id: 'cloud', word: 'Cloud', jp: 'くも', icon: '☁️', rarity: 1, bg: 'bg-gray-100' },
    { id: 'umbrella', word: 'Umbrella', jp: 'かさ', icon: '☂️', rarity: 1, bg: 'bg-purple-50' },
    { id: 'fish', word: 'Fish', jp: 'さかな', icon: '🐟', rarity: 1, bg: 'bg-blue-50' },
    { id: 'bug', word: 'Bug', jp: 'むし', icon: '🐛', rarity: 1, bg: 'bg-green-50' },
    { id: 'ant', word: 'Ant', jp: 'あり', icon: '🐜', rarity: 1, bg: 'bg-stone-200' },
    { id: 'eye', word: 'Eye', jp: 'め', icon: '👁️', rarity: 1, bg: 'bg-stone-50' },
    { id: 'ear', word: 'Ear', jp: 'みみ', icon: '👂', rarity: 1, bg: 'bg-orange-50' },
    { id: 'mouth', word: 'Mouth', jp: 'くち', icon: '👄', rarity: 1, bg: 'bg-pink-50' },
    { id: 'hand', word: 'Hand', jp: 'て', icon: '✋', rarity: 1, bg: 'bg-orange-50' },
    { id: 'foot', word: 'Foot', jp: 'あし', icon: '🦶', rarity: 1, bg: 'bg-orange-50' },
    { id: 'nose', word: 'Nose', jp: 'はな', icon: '👃', rarity: 1, bg: 'bg-orange-50' },
    { id: 'door', word: 'Door', jp: 'ドア', icon: '🚪', rarity: 1, bg: 'bg-yellow-100' },
    { id: 'bed', word: 'Bed', jp: 'ベッド', icon: '🛏️', rarity: 1, bg: 'bg-blue-50' },
    { id: 'bath', word: 'Bath', jp: 'おふろ', icon: '🛁', rarity: 1, bg: 'bg-cyan-50' },
    { id: 'clock', word: 'Clock', jp: 'とけい', icon: '⏰', rarity: 1, bg: 'bg-red-50' },
    { id: 'phone', word: 'Phone', jp: 'でんわ', icon: '📱', rarity: 1, bg: 'bg-slate-100' },
    { id: 'water', word: 'Water', jp: 'みず', icon: '💧', rarity: 1, bg: 'bg-blue-50' },
    { id: 'fire_e', word: 'Fire', jp: 'ひ', icon: '🔥', rarity: 1, bg: 'bg-red-50' },
    { id: 'key', word: 'Key', jp: 'かぎ', icon: '🔑', rarity: 1, bg: 'bg-yellow-100' },
    { id: 'bag', word: 'Bag', jp: 'かばん', icon: '🎒', rarity: 1, bg: 'bg-red-50' },
    { id: 'chair', word: 'Chair', jp: 'いす', icon: '🪑', rarity: 1, bg: 'bg-stone-100' },
    { id: 'desk', word: 'Desk', jp: 'つくえ', icon: '🧱', rarity: 1, bg: 'bg-amber-100' }, // using brick for desk-like color or use another icon
    { id: 'cup', word: 'Cup', jp: 'コップ', icon: '🥤', rarity: 1, bg: 'bg-blue-50' },
    { id: 'spoon', word: 'Spoon', jp: 'スプーン', icon: '🥄', rarity: 1, bg: 'bg-slate-100' },
    { id: 'fork', word: 'Fork', jp: 'フォーク', icon: '🔱', rarity: 1, bg: 'bg-slate-100' },
    { id: 'scissors', word: 'Scissors', jp: 'はさみ', icon: '✂️', rarity: 1, bg: 'bg-slate-100' },
    { id: 'notebook', word: 'Notebook', jp: 'ノート', icon: '📓', rarity: 1, bg: 'bg-gray-100' },
    { id: 'house', word: 'House', jp: 'いえ', icon: '🏠', rarity: 1, bg: 'bg-yellow-50' },
    { id: 'school', word: 'School', jp: 'がっこう', icon: '🏫', rarity: 1, bg: 'bg-stone-100' },
    { id: 'park', word: 'Park', jp: 'こうえん', icon: '⛲', rarity: 1, bg: 'bg-sky-50' },
    { id: 'shop', word: 'Shop', jp: 'おみせ', icon: '🏪', rarity: 1, bg: 'bg-blue-50' },
    { id: 'tooth', word: 'Tooth', jp: 'は', icon: '🦷', rarity: 1, bg: 'bg-white' },
    { id: 'glasses', word: 'Glasses', jp: 'めがね', icon: '👓', rarity: 1, bg: 'bg-slate-100' },
    { id: 'watch', word: 'Watch', jp: 'うでどけい', icon: '⌚', rarity: 1, bg: 'bg-slate-800 text-white' },
    { id: 'tv', word: 'TV', jp: 'テレビ', icon: '📺', rarity: 1, bg: 'bg-gray-200' },
    { id: 'tomato', word: 'Tomato', jp: 'トマト', icon: '🍅', rarity: 1, bg: 'bg-red-100' },
    { id: 'potato', word: 'Potato', jp: 'じゃがいも', icon: '🥔', rarity: 1, bg: 'bg-amber-100' },
    { id: 'carrot', word: 'Carrot', jp: 'にんじん', icon: '🥕', rarity: 1, bg: 'bg-orange-100' },
    { id: 'corn', word: 'Corn', jp: 'とうもろこし', icon: '🌽', rarity: 1, bg: 'bg-yellow-100' },
    { id: 'onion', word: 'Onion', jp: 'たまねぎ', icon: '🧅', rarity: 1, bg: 'bg-amber-50' },
    { id: 'leaf', word: 'Leaf', jp: 'はっぱ', icon: '🍃', rarity: 1, bg: 'bg-green-50' },
    { id: 'seed', word: 'Seed', jp: 'たね', icon: '🌰', rarity: 1, bg: 'bg-stone-200' }, // chestnut as seed
    { id: 'pants', word: 'Pants', jp: 'ズボン', icon: '👖', rarity: 1, bg: 'bg-blue-100' },
    { id: 'skirt', word: 'Skirt', jp: 'スカート', icon: '👗', rarity: 1, bg: 'bg-pink-100' }, // dress for skirt
    { id: 'coat', word: 'Coat', jp: 'コート', icon: '🧥', rarity: 1, bg: 'bg-stone-200' },
    { id: 'bikini', word: 'Swimsuit', jp: 'みずぎ', icon: '👙', rarity: 1, bg: 'bg-pink-50' },
    { id: 'lipstick', word: 'Lipstick', jp: 'くちべに', icon: '💄', rarity: 1, bg: 'bg-red-100' },
    { id: 'baby', word: 'Baby', jp: 'あかちゃん', icon: '👶', rarity: 1, bg: 'bg-orange-50' },
    { id: 'boy', word: 'Boy', jp: 'おとこのこ', icon: '👦', rarity: 1, bg: 'bg-blue-50' },
    { id: 'girl', word: 'Girl', jp: 'おんなのこ', icon: '👧', rarity: 1, bg: 'bg-pink-50' },
    { id: 'man', word: 'Man', jp: 'おとこのひと', icon: '👨', rarity: 1, bg: 'bg-blue-50' },
    { id: 'woman', word: 'Woman', jp: 'おんなのひと', icon: '👩', rarity: 1, bg: 'bg-pink-50' },
    { id: 'grandpa', word: 'Grandpa', jp: 'おじいちゃん', icon: '👴', rarity: 1, bg: 'bg-gray-100' },
    { id: 'grandma', word: 'Grandma', jp: 'おばあちゃん', icon: '👵', rarity: 1, bg: 'bg-gray-100' },
    { id: 'teacher', word: 'Teacher', jp: 'せんせい', icon: '👩‍🏫', rarity: 1, bg: 'bg-blue-50' },
    { id: 'doctor', word: 'Doctor', jp: 'おいしゃさん', icon: '🩺', rarity: 1, bg: 'bg-white border' },
    { id: 'police_o', word: 'Police', jp: 'おまわりさん', icon: '👮', rarity: 1, bg: 'bg-blue-100' },
    { id: 'paper', word: 'Paper', jp: 'かみ', icon: '📄', rarity: 1, bg: 'bg-white border' },
    { id: 'box', word: 'Box', jp: 'はこ', icon: '📦', rarity: 1, bg: 'bg-amber-100' },
    { id: 'trash', word: 'Trash', jp: 'ゴミ', icon: '🗑️', rarity: 1, bg: 'bg-gray-100' },
    { id: 'money', word: 'Money', jp: 'おかね', icon: '💴', rarity: 1, bg: 'bg-yellow-50' },
    { id: 'wallet', word: 'Wallet', jp: 'さいふ', icon: '👛', rarity: 1, bg: 'bg-red-50' },
    { id: 'calendar', word: 'Calendar', jp: 'カレンダー', icon: '📅', rarity: 1, bg: 'bg-white' },
    { id: 'camera', word: 'Camera', jp: 'カメラ', icon: '📷', rarity: 1, bg: 'bg-slate-200' },
    { id: 'video', word: 'Video', jp: 'ビデオ', icon: '📹', rarity: 1, bg: 'bg-slate-300' },
    { id: 'telephone', word: 'Telephone', jp: 'でんわ', icon: '☎️', rarity: 1, bg: 'bg-red-50' },
    { id: 'soap', word: 'Soap', jp: 'せっけん', icon: '🧼', rarity: 1, bg: 'bg-pink-50' },
    { id: 'sponge', word: 'Sponge', jp: 'スポンジ', icon: '🧽', rarity: 1, bg: 'bg-yellow-100' },
    { id: 'toilet', word: 'Toilet', jp: 'トイレ', icon: '🚽', rarity: 1, bg: 'bg-white' },
    { id: 'broom', word: 'Broom', jp: 'ほうき', icon: '🧹', rarity: 1, bg: 'bg-amber-50' },
    { id: 'bucket', word: 'Bucket', jp: 'バケツ', icon: '🪣', rarity: 1, bg: 'bg-blue-100' },
    { id: 'ladder', word: 'Ladder', jp: 'はしご', icon: '🪜', rarity: 1, bg: 'bg-stone-200' },
    { id: 'hammer', word: 'Hammer', jp: 'ハンマー', icon: '🔨', rarity: 1, bg: 'bg-slate-100' },
    { id: 'nut', word: 'Nut', jp: 'ナッツ', icon: '🥜', rarity: 1, bg: 'bg-amber-200' },
    { id: 'mushroom', word: 'Mushroom', jp: 'きのこ', icon: '🍄', rarity: 1, bg: 'bg-red-100' },
    { id: 'bamboo', word: 'Bamboo', jp: 'たけ', icon: '🎍', rarity: 1, bg: 'bg-green-100' },
    { id: 'stone', word: 'Stone', jp: 'いし', icon: '🪨', rarity: 1, bg: 'bg-stone-400' },
    { id: 'sand', word: 'Sand', jp: 'すな', icon: '🏖️', rarity: 1, bg: 'bg-yellow-50' },
    { id: 'wave', word: 'Wave', jp: 'なみ', icon: '🌊', rarity: 1, bg: 'bg-blue-200' },
    { id: 'hotspring', word: 'Hot Spring', jp: 'おんせん', icon: '♨️', rarity: 1, bg: 'bg-stone-100' },
    { id: 'hospital', word: 'Hospital', jp: 'びょういん', icon: '🏥', rarity: 1, bg: 'bg-pink-50' },
    { id: 'postoffice', word: 'Post Office', jp: 'ゆうびんきょく', icon: '🏣', rarity: 1, bg: 'bg-red-50' },
    { id: 'bank', word: 'Bank', jp: 'ぎんこう', icon: '🏦', rarity: 1, bg: 'bg-blue-50' },
    { id: 'hotel', word: 'Hotel', jp: 'ホテル', icon: '🏨', rarity: 1, bg: 'bg-yellow-50' },
    { id: 'station', word: 'Station', jp: 'えき', icon: '🚉', rarity: 1, bg: 'bg-gray-100' },
    { id: 'letter', word: 'Letter', jp: 'てがみ', icon: '✉️', rarity: 1, bg: 'bg-white' },
    { id: 'envelope', word: 'Envelope', jp: 'ふうとう', icon: '📨', rarity: 1, bg: 'bg-white' },
    { id: 'package', word: 'Package', jp: 'こづつみ', icon: '📦', rarity: 1, bg: 'bg-amber-100' },
    { id: 'card', word: 'Card', jp: 'カード', icon: '🃏', rarity: 1, bg: 'bg-white' },
    { id: 'red', word: 'Red', jp: 'あか', icon: '🔴', rarity: 1, bg: 'bg-red-200' },
    { id: 'blue', word: 'Blue', jp: 'あお', icon: '🔵', rarity: 1, bg: 'bg-blue-200' },
    { id: 'green', word: 'Green', jp: 'みどり', icon: '🟢', rarity: 1, bg: 'bg-green-200' },
    { id: 'yellow', word: 'Yellow', jp: 'きいろ', icon: '🟡', rarity: 1, bg: 'bg-yellow-200' },
    { id: 'white', word: 'White', jp: 'しろ', icon: '⚪', rarity: 1, bg: 'bg-gray-50' },
    { id: 'black', word: 'Black', jp: 'くろ', icon: '⚫', rarity: 1, bg: 'bg-stone-400' },
    { id: 'ship', word: 'Ship', jp: 'ふね', icon: '🚢', rarity: 1, bg: 'bg-blue-100' },
    { id: 'bicycle', word: 'Bicycle', jp: 'じてんしゃ', icon: '🚲', rarity: 1, bg: 'bg-stone-100' },
    { id: 'stop', word: 'Stop', jp: 'とまれ', icon: '🛑', rarity: 1, bg: 'bg-red-100' },
    { id: 'light', word: 'Light', jp: 'ライト', icon: '💡', rarity: 1, bg: 'bg-yellow-50' },
    { id: 'battery', word: 'Battery', jp: 'でんち', icon: '🔋', rarity: 1, bg: 'bg-green-50' },
    { id: 'plug', word: 'Plug', jp: 'プラグ', icon: '🔌', rarity: 1, bg: 'bg-gray-100' },
    { id: 'keyboard', word: 'Keyboard', jp: 'キーボード', icon: '⌨️', rarity: 1, bg: 'bg-slate-100' },
    { id: 'mouse_c', word: 'Mouse', jp: 'マウス', icon: '🖱️', rarity: 1, bg: 'bg-white' },
    { id: 'disk', word: 'Disk', jp: 'ディスク', icon: '💿', rarity: 1, bg: 'bg-slate-200' },
    { id: 'file', word: 'File', jp: 'ファイル', icon: '📁', rarity: 1, bg: 'bg-yellow-100' },
    { id: 'clip', word: 'Clip', jp: 'クリップ', icon: '📎', rarity: 1, bg: 'bg-slate-200' },
    { id: 'pin', word: 'Pin', jp: 'ピン', icon: '📌', rarity: 1, bg: 'bg-red-50' },
    { id: 'lock', word: 'Lock', jp: 'じょう', icon: '🔒', rarity: 1, bg: 'bg-amber-100' },
    { id: 'bell', word: 'Bell', jp: 'ベル', icon: '🔔', rarity: 1, bg: 'bg-yellow-100' },
    { id: 'mag_glass', word: 'Magnifier', jp: 'むしめがね', icon: '🔎', rarity: 1, bg: 'bg-slate-200' },
    { id: 'candle', word: 'Candle', jp: 'ろうそく', icon: '🕯️', rarity: 1, bg: 'bg-orange-50' },
    { id: 'flashlight', word: 'Flashlight', jp: 'かいちゅうでんとう', icon: '🔦', rarity: 1, bg: 'bg-slate-300' },
    { id: 'gift_c', word: 'Gift', jp: 'おくりもの', icon: '🎁', rarity: 1, bg: 'bg-red-100' },
    { id: 'heart', word: 'Heart', jp: 'ハート', icon: '❤️', rarity: 1, bg: 'bg-red-50' },
    { id: 'broken_h', word: 'Broken Heart', jp: 'しつれん', icon: '💔', rarity: 1, bg: 'bg-red-50' },

    // --- Rare (★2) Fun Actions, Animals & Objects ---
    { id: 'grape', word: 'Grape', jp: 'ぶどう', icon: '🍇', rarity: 2, bg: 'bg-purple-100' },
    { id: 'strawberry', word: 'Strawberry', jp: 'いちご', icon: '🍓', rarity: 2, bg: 'bg-red-100' },
    { id: 'melon', word: 'Melon', jp: 'メロン', icon: '🍈', rarity: 2, bg: 'bg-green-100' },
    { id: 'peach', word: 'Peach', jp: 'もも', icon: '🍑', rarity: 2, bg: 'bg-pink-100' },
    { id: 'cherry', word: 'Cherry', jp: 'さくらんぼ', icon: '🍒', rarity: 2, bg: 'bg-rose-100' },
    { id: 'lemon', word: 'Lemon', jp: 'レモン', icon: '🍋', rarity: 2, bg: 'bg-yellow-200' },
    { id: 'pineapple', word: 'Pineapple', jp: 'パイナップル', icon: '🍍', rarity: 2, bg: 'bg-yellow-100' },
    { id: 'kiwi', word: 'Kiwi', jp: 'キウイ', icon: '🥝', rarity: 2, bg: 'bg-green-100' },
    { id: 'mango', word: 'Mango', jp: 'マンゴー', icon: '🥭', rarity: 2, bg: 'bg-orange-100' },
    { id: 'coconut', word: 'Coconut', jp: 'ココナッツ', icon: '🥥', rarity: 2, bg: 'bg-stone-100' },
    { id: 'lion', word: 'Lion', jp: 'ライオン', icon: '🦁', rarity: 2, bg: 'bg-yellow-100' },
    { id: 'tiger', word: 'Tiger', jp: 'とら', icon: '🐯', rarity: 2, bg: 'bg-orange-200' },
    { id: 'bear', word: 'Bear', jp: 'くま', icon: '🐻', rarity: 2, bg: 'bg-amber-200' },
    { id: 'panda', word: 'Panda', jp: 'パンダ', icon: '🐼', rarity: 2, bg: 'bg-stone-100' },
    { id: 'koala', word: 'Koala', jp: 'コアラ', icon: '🐨', rarity: 2, bg: 'bg-slate-200' },
    { id: 'rabbit', word: 'Rabbit', jp: 'うさぎ', icon: '🐰', rarity: 2, bg: 'bg-pink-50' },
    { id: 'frog', word: 'Frog', jp: 'かえる', icon: '🐸', rarity: 2, bg: 'bg-green-100' },
    { id: 'turtle', word: 'Turtle', jp: 'かめ', icon: '🐢', rarity: 2, bg: 'bg-emerald-100' },
    { id: 'penguin', word: 'Penguin', jp: 'ペンギン', icon: '🐧', rarity: 2, bg: 'bg-blue-100' },
    { id: 'octopus', word: 'Octopus', jp: 'たこ', icon: '🐙', rarity: 2, bg: 'bg-red-100' },
    { id: 'squid', word: 'Squid', jp: 'いか', icon: '🦑', rarity: 2, bg: 'bg-white' },
    { id: 'shrimp', word: 'Shrimp', jp: 'えび', icon: '🦐', rarity: 2, bg: 'bg-red-50' },
    { id: 'crab', word: 'Crab', jp: 'かに', icon: '🦀', rarity: 2, bg: 'bg-red-100' },
    { id: 'puffer', word: 'Blowfish', jp: 'ふぐ', icon: '🐡', rarity: 2, bg: 'bg-yellow-100' },
    { id: 'dolphin', word: 'Dolphin', jp: 'イルカ', icon: '🐬', rarity: 2, bg: 'bg-blue-200' },
    { id: 'shark_r', word: 'Shark', jp: 'さめ', icon: '🦈', rarity: 2, bg: 'bg-slate-300' }, // Rarity 2 ver? Maybe keep 3
    { id: 'horse', word: 'Horse', jp: 'うま', icon: '🐴', rarity: 2, bg: 'bg-amber-100' },
    { id: 'zebra', word: 'Zebra', jp: 'しまうま', icon: '🦓', rarity: 2, bg: 'bg-stone-100' },
    { id: 'sheep', word: 'Sheep', jp: 'ひつじ', icon: '🐑', rarity: 2, bg: 'bg-white' },
    { id: 'goat', word: 'Goat', jp: 'やぎ', icon: '🐐', rarity: 2, bg: 'bg-stone-100' },
    { id: 'camel', word: 'Camel', jp: 'ラクダ', icon: '🐪', rarity: 2, bg: 'bg-amber-100' },
    { id: 'elephant', word: 'Elephant', jp: 'ぞう', icon: '🐘', rarity: 2, bg: 'bg-slate-200' },
    { id: 'rhino', word: 'Rhino', jp: 'さい', icon: '🦏', rarity: 2, bg: 'bg-slate-300' },
    { id: 'hippo', word: 'Hippo', jp: 'かば', icon: '🦛', rarity: 2, bg: 'bg-purple-100' },
    { id: 'giraffe', word: 'Giraffe', jp: 'きりん', icon: '🦒', rarity: 2, bg: 'bg-yellow-200' },
    { id: 'kangaroo', word: 'Kangaroo', jp: 'カンガルー', icon: '🦘', rarity: 2, bg: 'bg-amber-100' },
    { id: 'monkey', word: 'Monkey', jp: 'さる', icon: '🐵', rarity: 2, bg: 'bg-amber-200' },
    { id: 'gorilla', word: 'Gorilla', jp: 'ゴリラ', icon: '🦍', rarity: 2, bg: 'bg-black text-gray-500' },
    { id: 'wolf', word: 'Wolf', jp: 'おおかみ', icon: '🐺', rarity: 2, bg: 'bg-slate-300' },
    { id: 'fox', word: 'Fox', jp: 'きつね', icon: '🦊', rarity: 2, bg: 'bg-orange-200' },
    { id: 'raccoon', word: 'Raccoon', jp: 'あらいぐま', icon: '🦝', rarity: 2, bg: 'bg-gray-200' },
    { id: 'boar', word: 'Boar', jp: 'いのしし', icon: '🐗', rarity: 2, bg: 'bg-stone-300' },
    { id: 'deer', word: 'Deer', jp: 'しか', icon: '🦌', rarity: 2, bg: 'bg-amber-100' },
    { id: 'owl', word: 'Owl', jp: 'ふくろう', icon: '🦉', rarity: 2, bg: 'bg-stone-200' },
    { id: 'eagle', word: 'Eagle', jp: 'わし', icon: '🦅', rarity: 2, bg: 'bg-stone-300' },
    { id: 'duck', word: 'Duck', jp: 'あひる', icon: '🦆', rarity: 2, bg: 'bg-green-100' },
    { id: 'swan', word: 'Swan', jp: 'はくちょう', icon: '🦢', rarity: 2, bg: 'bg-white' },
    { id: 'bat', word: 'Bat', jp: 'こうもり', icon: '🦇', rarity: 2, bg: 'bg-gray-400' },
    { id: 'snake', word: 'Snake', jp: 'へび', icon: '🐍', rarity: 2, bg: 'bg-green-100' },
    { id: 'lizard', word: 'Lizard', jp: 'とかげ', icon: '🦎', rarity: 2, bg: 'bg-green-100' },
    { id: 'burger', word: 'Burger', jp: 'ハンバーガー', icon: '🍔', rarity: 2, bg: 'bg-orange-100' },
    { id: 'fries', word: 'Fries', jp: 'ポテト', icon: '🍟', rarity: 2, bg: 'bg-yellow-100' },
    { id: 'pizza', word: 'Pizza', jp: 'ピザ', icon: '🍕', rarity: 2, bg: 'bg-orange-50' },
    { id: 'hotdog', word: 'Hot Dog', jp: 'ホットドッグ', icon: '🌭', rarity: 2, bg: 'bg-orange-100' },
    { id: 'sandwich', word: 'Sandwich', jp: 'サンドイッチ', icon: '🥪', rarity: 2, bg: 'bg-yellow-50' },
    { id: 'taco', word: 'Taco', jp: 'タコス', icon: '🌮', rarity: 2, bg: 'bg-yellow-100' },
    { id: 'burrito', word: 'Burrito', jp: 'ブリトー', icon: '🌯', rarity: 2, bg: 'bg-stone-100' },
    { id: 'donut', word: 'Donut', jp: 'ドーナツ', icon: '🍩', rarity: 2, bg: 'bg-pink-100' },
    { id: 'cookie', word: 'Cookie', jp: 'クッキー', icon: '🍪', rarity: 2, bg: 'bg-amber-100' },
    { id: 'pancake', word: 'Pancake', jp: 'パンケーキ', icon: '🥞', rarity: 2, bg: 'bg-yellow-100' },
    { id: 'icecream', word: 'Ice Cream', jp: 'アイス', icon: '🍦', rarity: 2, bg: 'bg-sky-50' },
    { id: 'cake', word: 'Cake', jp: 'ケーキ', icon: '🍰', rarity: 2, bg: 'bg-rose-50' },
    { id: 'cupcake', word: 'Cupcake', jp: 'カップケーキ', icon: '🧁', rarity: 2, bg: 'bg-pink-100' },
    { id: 'pie', word: 'Pie', jp: 'パイ', icon: '🥧', rarity: 2, bg: 'bg-amber-100' },
    { id: 'chocolate', word: 'Chocolate', jp: 'チョコ', icon: '🍫', rarity: 2, bg: 'bg-stone-300' },
    { id: 'candy', word: 'Candy', jp: 'キャンディ', icon: '🍬', rarity: 2, bg: 'bg-purple-50' },
    { id: 'lollipop', word: 'Lollipop', jp: 'ペロペロキャンディ', icon: '🍭', rarity: 2, bg: 'bg-pink-100' },
    { id: 'custard', word: 'Custard', jp: 'プリン', icon: '🍮', rarity: 2, bg: 'bg-yellow-100' },
    { id: 'honey', word: 'Honey', jp: 'はちみつ', icon: '🍯', rarity: 2, bg: 'bg-yellow-200' },
    { id: 'popcorn', word: 'Popcorn', jp: 'ポップコーン', icon: '🍿', rarity: 2, bg: 'bg-red-50' },
    { id: 'bento', word: 'Lunch Box', jp: 'おべんとう', icon: '🍱', rarity: 2, bg: 'bg-stone-100' },
    { id: 'sushi', word: 'Sushi', jp: 'すし', icon: '🍣', rarity: 2, bg: 'bg-orange-50' },
    { id: 'tempura', word: 'Tempura', jp: 'てんぷら', icon: '🍤', rarity: 2, bg: 'bg-yellow-50' },
    { id: 'dango', word: 'Dango', jp: 'だんご', icon: '🍡', rarity: 2, bg: 'bg-pink-50' },
    { id: 'train', word: 'Train', jp: 'でんしゃ', icon: '🚃', rarity: 2, bg: 'bg-green-100' },
    { id: 'shinkansen', word: 'Bullet Train', jp: 'しんかんせん', icon: '🚅', rarity: 2, bg: 'bg-blue-50' },
    { id: 'locomotive', word: 'Steam Train', jp: 'きかんしゃ', icon: '🚂', rarity: 2, bg: 'bg-black text-gray-400' },
    { id: 'bike', word: 'Bike', jp: 'じてんしゃ', icon: '🚲', rarity: 2, bg: 'bg-blue-50' },
    { id: 'scooter', word: 'Scooter', jp: 'スクーター', icon: '🛵', rarity: 2, bg: 'bg-orange-50' },
    { id: 'skateboard', word: 'Skateboard', jp: 'スケボー', icon: '🛹', rarity: 2, bg: 'bg-green-100' },
    { id: 'boat', word: 'Boat', jp: 'ボート', icon: '🚤', rarity: 2, bg: 'bg-cyan-100' },
    { id: 'truck', word: 'Truck', jp: 'トラック', icon: '🚚', rarity: 2, bg: 'bg-slate-200' },
    { id: 'police', word: 'Police Car', jp: 'パトカー', icon: '🚓', rarity: 2, bg: 'bg-stone-100' },
    { id: 'fire', word: 'Fire Engine', jp: 'しょうぼうしゃ', icon: '🚒', rarity: 2, bg: 'bg-red-200' },
    { id: 'ambulance', word: 'Ambulance', jp: 'きゅうきゅうしゃ', icon: '🚑', rarity: 2, bg: 'bg-slate-50' },
    { id: 'tractor', word: 'Tractor', jp: 'トラクター', icon: '🚜', rarity: 2, bg: 'bg-green-200' },
    { id: 'moon', word: 'Moon', jp: 'つき', icon: '🌙', rarity: 2, bg: 'bg-indigo-100' },
    { id: 'star', word: 'Star', jp: 'ほし', icon: '⭐', rarity: 2, bg: 'bg-yellow-100' },
    { id: 'sparkles', word: 'Sparkles', jp: 'キラキラ', icon: '✨', rarity: 2, bg: 'bg-yellow-50' },
    { id: 'comet', word: 'Comet', jp: 'すいせい', icon: '☄️', rarity: 2, bg: 'bg-indigo-200' },
    { id: 'camera_c', word: 'Camera', jp: 'カメラ', icon: '📷', rarity: 2, bg: 'bg-stone-200' },
    { id: 'computer', word: 'Computer', jp: 'パソコン', icon: '💻', rarity: 2, bg: 'bg-slate-200' },
    { id: 'robot', word: 'Robot', jp: 'ロボット', icon: '🤖', rarity: 2, bg: 'bg-gray-200' },
    { id: 'music', word: 'Music', jp: 'おんがく', icon: '🎵', rarity: 2, bg: 'bg-pink-100' },
    { id: 'piano', word: 'Piano', jp: 'ピアノ', icon: '🎹', rarity: 2, bg: 'bg-white' },
    { id: 'guitar', word: 'Guitar', jp: 'ギター', icon: '🎸', rarity: 2, bg: 'bg-red-50' },
    { id: 'violin', word: 'Violin', jp: 'バイオリン', icon: '🎻', rarity: 2, bg: 'bg-amber-100' },
    { id: 'drum', word: 'Drum', jp: 'たいこ', icon: '🥁', rarity: 2, bg: 'bg-red-100' },
    { id: 'trumpet', word: 'Trumpet', jp: 'トランペット', icon: '🎺', rarity: 2, bg: 'bg-yellow-100' },
    { id: 'sax', word: 'Saxophone', jp: 'サックス', icon: '🎷', rarity: 2, bg: 'bg-yellow-100' },
    { id: 'accordion', word: 'Accordion', jp: 'アコーディオン', icon: '🪗', rarity: 2, bg: 'bg-red-200' },
    { id: 'mic', word: 'Mic', jp: 'マイク', icon: '🎤', rarity: 2, bg: 'bg-slate-200' },
    { id: 'headphone', word: 'Headphone', jp: 'ヘッドホン', icon: '🎧', rarity: 2, bg: 'bg-gray-100' },
    { id: 'balloon', word: 'Balloon', jp: 'ふうせん', icon: '🎈', rarity: 2, bg: 'bg-red-50' },
    { id: 'baseball', word: 'Baseball', jp: 'やきゅう', icon: '⚾', rarity: 2, bg: 'bg-white' },
    { id: 'soccer', word: 'Soccer', jp: 'サッカー', icon: '⚽', rarity: 2, bg: 'bg-white' },
    { id: 'tennis', word: 'Tennis', jp: 'テニス', icon: '🎾', rarity: 2, bg: 'bg-yellow-200' },
    { id: 'basketball', word: 'Basketball', jp: 'バスケ', icon: '🏀', rarity: 2, bg: 'bg-orange-200' },
    { id: 'volleyball', word: 'Volleyball', jp: 'バレー', icon: '🏐', rarity: 2, bg: 'bg-white' },
    { id: 'rugby', word: 'Rugby', jp: 'ラグビー', icon: '🏉', rarity: 2, bg: 'bg-stone-100' },
    { id: 'bowling', word: 'Bowling', jp: 'ボウリング', icon: '🎳', rarity: 2, bg: 'bg-white' },
    { id: 'goal', word: 'Goal', jp: 'ゴール', icon: '🥅', rarity: 2, bg: 'bg-gray-100' },
    { id: 'ski', word: 'Ski', jp: 'スキー', icon: '🎿', rarity: 2, bg: 'bg-blue-50' },
    { id: 'sled', word: 'Sled', jp: 'そり', icon: '🛷', rarity: 2, bg: 'bg-red-100' },
    { id: 'skate', word: 'Skate', jp: 'スケート', icon: '⛸️', rarity: 2, bg: 'bg-white' },
    { id: 'cricket', word: 'Cricket', jp: 'クリケット', icon: '🏏', rarity: 2, bg: 'bg-amber-100' },
    { id: 'badminton', word: 'Badminton', jp: 'バドミントン', icon: '🏸', rarity: 2, bg: 'bg-white' },
    { id: 'tent', word: 'Tent', jp: 'テント', icon: '⛺', rarity: 2, bg: 'bg-orange-100' },
    { id: 'fishing', word: 'Fishing', jp: 'つり', icon: '🎣', rarity: 2, bg: 'bg-blue-50' },
    { id: 'kite', word: 'Kite', jp: 'たこあげ', icon: '🪁', rarity: 2, bg: 'bg-red-50' },
    { id: 'bow', word: 'Bow', jp: 'ゆみ', icon: '🏹', rarity: 2, bg: 'bg-amber-50' },
    { id: 'joystick', word: 'Game', jp: 'ゲーム', icon: '🕹️', rarity: 2, bg: 'bg-slate-200' },

    // --- Super Rare (★3) Cool & Amazing Things ---
    { id: 'plane', word: 'Plane', jp: 'ひこうき', icon: '✈️', rarity: 3, bg: 'bg-sky-200' },
    { id: 'helicopter', word: 'Helicopter', jp: 'ヘリコプター', icon: '🚁', rarity: 3, bg: 'bg-stone-300' },
    { id: 'fighter', word: 'Fighter Jet', jp: 'せんとうき', icon: '🛩️', rarity: 3, bg: 'bg-slate-400' },
    { id: 'rocket', word: 'Rocket', jp: 'ロケット', icon: '🚀', rarity: 3, bg: 'bg-indigo-200' },
    { id: 'ufo', word: 'UFO', jp: 'UFO', icon: '🛸', rarity: 3, bg: 'bg-purple-200' },
    { id: 'satellite', word: 'Satellite', jp: 'えいせい', icon: '🛰️', rarity: 3, bg: 'bg-slate-400' },
    { id: 'dinosaur', word: 'Dinosaur', jp: 'きょうりゅう', icon: '🦖', rarity: 3, bg: 'bg-green-200' },
    { id: 't-rex', word: 'T-Rex', jp: 'ティラノ', icon: '🦖', rarity: 3, bg: 'bg-green-300' }, // same icon, different name
    { id: 'sauropod', word: 'Bronto', jp: 'ブロント', icon: '🦕', rarity: 3, bg: 'bg-blue-300' },
    { id: 'shark', word: 'Shark', jp: 'さめ', icon: '🦈', rarity: 3, bg: 'bg-slate-300' },
    { id: 'whale', word: 'Whale', jp: 'くじら', icon: '🐳', rarity: 3, bg: 'bg-blue-200' },
    { id: 'dolphin_s', word: 'Dolphin', jp: 'イルカ', icon: '🐬', rarity: 3, bg: 'bg-cyan-200' }, // Rare version
    { id: 'swordfish', word: 'Marlin', jp: 'カジキ', icon: '🐟', rarity: 3, bg: 'bg-blue-400' }, // Use generic fish but cool name/color
    { id: 'crocodile', word: 'Crocodile', jp: 'ワニ', icon: '🐊', rarity: 3, bg: 'bg-green-300' },
    { id: 'scorpion', word: 'Scorpion', jp: 'サソリ', icon: '🦂', rarity: 3, bg: 'bg-amber-300' },
    { id: 'spider', word: 'Spider', jp: 'クモ', icon: '🕷️', rarity: 3, bg: 'bg-black text-gray-400' },
    { id: 'web', word: 'Spider Web', jp: 'クモのす', icon: '🕸️', rarity: 3, bg: 'bg-slate-200' },
    { id: 'rainbow', word: 'Rainbow', jp: 'にじ', icon: '🌈', rarity: 3, bg: 'bg-sky-100' },
    { id: 'snowman', word: 'Snowman', jp: 'ゆきだるま', icon: '⛄', rarity: 3, bg: 'bg-slate-100' },
    { id: 'snowflake', word: 'Snowflake', jp: 'ゆきのけっしょう', icon: '❄️', rarity: 3, bg: 'bg-blue-50' },
    { id: 'cyclone', word: 'Tornado', jp: 'たつまき', icon: '🌪️', rarity: 3, bg: 'bg-gray-300' },
    { id: 'volcano', word: 'Volcano', jp: 'かざん', icon: '🌋', rarity: 3, bg: 'bg-stone-300' },
    { id: 'fuji', word: 'Mt Fuji', jp: 'ふじさん', icon: '🗻', rarity: 3, bg: 'bg-blue-100' },
    { id: 'earth', word: 'Earth', jp: 'ちきゅう', icon: '🌍', rarity: 3, bg: 'bg-blue-200' },
    { id: 'fullmoon', word: 'Full Moon', jp: 'まんげつ', icon: '🌕', rarity: 3, bg: 'bg-yellow-100' },
    { id: 'sun_face', word: 'Sun Face', jp: 'おひさま', icon: '🌞', rarity: 3, bg: 'bg-orange-100' },
    { id: 'ghost', word: 'Ghost', jp: 'おばけ', icon: '👻', rarity: 3, bg: 'bg-gray-300' },
    { id: 'skull', word: 'Skull', jp: 'ドクロ', icon: '💀', rarity: 3, bg: 'bg-gray-200' },
    { id: 'pumpkin', word: 'Pumpkin', jp: 'カボチャ', icon: '🎃', rarity: 3, bg: 'bg-orange-300' },
    { id: 'present', word: 'Gift', jp: 'プレゼント', icon: '🎁', rarity: 3, bg: 'bg-red-200' },
    { id: 'ring', word: 'Ring', jp: 'ゆびわ', icon: '💍', rarity: 3, bg: 'bg-cyan-100' },
    { id: 'gem', word: 'Gem', jp: 'ほうせき', icon: '💎', rarity: 3, bg: 'bg-cyan-200' },
    { id: 'trophy', word: 'Trophy', jp: 'トロフィー', icon: '🏆', rarity: 3, bg: 'bg-yellow-200' },
    { id: 'medal', word: 'Medal', jp: 'メダル', icon: '🥇', rarity: 3, bg: 'bg-yellow-300' },
    { id: 'medal_2', word: 'Silver Medal', jp: 'ぎんメダル', icon: '🥈', rarity: 3, bg: 'bg-gray-200' },
    { id: 'medal_3', word: 'Bronze Medal', jp: 'どうメダル', icon: '🥉', rarity: 3, bg: 'bg-amber-400' },
    { id: 'crown_s', word: 'Crown', jp: 'おうかん', icon: '👑', rarity: 3, bg: 'bg-yellow-300' },
    { id: 'ticket', word: 'Ticket', jp: 'チケット', icon: '🎫', rarity: 3, bg: 'bg-yellow-100' },
    { id: 'map', word: 'Map', jp: 'ちず', icon: '🗺️', rarity: 3, bg: 'bg-stone-100' },
    { id: 'compass', word: 'Compass', jp: 'コンパス', icon: '🧭', rarity: 3, bg: 'bg-stone-200' },
    { id: 'anchor', word: 'Anchor', jp: 'イカリ', icon: '⚓', rarity: 3, bg: 'bg-slate-300' },
    { id: 'sword', word: 'Sword', jp: 'けん', icon: '⚔️', rarity: 3, bg: 'bg-slate-200' },
    { id: 'shield', word: 'Shield', jp: 'たて', icon: '🛡️', rarity: 3, bg: 'bg-slate-200' },
    { id: 'bomb', word: 'Bomb', jp: 'ばくだん', icon: '💣', rarity: 3, bg: 'bg-black text-gray-500' },
    { id: 'ferris', word: 'Ferris Wheel', jp: 'かんらんしゃ', icon: '🎡', rarity: 3, bg: 'bg-pink-100' },
    { id: 'coaster', word: 'Roller Coaster', jp: 'ジェットコースター', icon: '🎢', rarity: 3, bg: 'bg-blue-100' },
    { id: 'carousel', word: 'Carousel', jp: 'メリーゴーランド', icon: '🎠', rarity: 3, bg: 'bg-yellow-100' },
    { id: 'circus', word: 'Circus', jp: 'サーカス', icon: '🎪', rarity: 3, bg: 'bg-red-100' },
    { id: 'fireworks', word: 'Fireworks', jp: 'はなび', icon: '🎆', rarity: 3, bg: 'bg-indigo-900 text-white' },
    { id: 'sparkler', word: 'Sparkler', jp: 'せんこうはなび', icon: '🎇', rarity: 3, bg: 'bg-yellow-100' },
    { id: 'samurai', word: 'Samurai', jp: 'さむらい', icon: '👘', rarity: 3, bg: 'bg-blue-800 text-white' }, // Kimono icon as placeholder
    { id: 'ninja', word: 'Ninja', jp: 'にんじゃ', icon: '🥷', rarity: 3, bg: 'bg-black text-gray-500' },
    { id: 'king', word: 'King', jp: 'おうさま', icon: '🤴', rarity: 3, bg: 'bg-yellow-200' },
    { id: 'queen', word: 'Queen', jp: 'じょおうさま', icon: '👸', rarity: 3, bg: 'bg-yellow-200' },
    { id: 'prince', word: 'Prince', jp: 'おうじさま', icon: '🤴', rarity: 3, bg: 'bg-blue-100' },
    { id: 'princess', word: 'Princess', jp: 'おひめさま', icon: '👸', rarity: 3, bg: 'bg-pink-100' },
    { id: 'bride', word: 'Bride', jp: 'はなよめ', icon: '👰', rarity: 3, bg: 'bg-white' },
    { id: 'superhero', word: 'Hero', jp: 'ヒーロー', icon: '🦸', rarity: 3, bg: 'bg-red-200' },
    { id: 'villain', word: 'Villain', jp: 'あくやく', icon: '🦹', rarity: 3, bg: 'bg-purple-200' },
    { id: 'wizard', word: 'Wizard', jp: 'まほうつかい', icon: '🧙', rarity: 3, bg: 'bg-indigo-200' },
    { id: 'fairy', word: 'Fairy', jp: 'ようせい', icon: '🧚', rarity: 3, bg: 'bg-green-100' },
    { id: 'vampire', word: 'Vampire', jp: 'ヴァンパイア', icon: '🧛', rarity: 3, bg: 'bg-gray-800 text-white' },
    { id: 'zombie', word: 'Zombie', jp: 'ゾンビ', icon: '🧟', rarity: 3, bg: 'bg-green-700 text-white' },
    { id: 'merperson', word: 'Mermaid', jp: 'にんぎょ', icon: '🧜', rarity: 3, bg: 'bg-blue-100' },
    { id: 'elf', word: 'Elf', jp: 'エルフ', icon: '🧝', rarity: 3, bg: 'bg-green-100' },

    // --- Ultra Rare (★4) Legendary & Myths & Special ---
    { id: 'dragon', word: 'Dragon', jp: 'ドラゴン', icon: '🐉', rarity: 4, bg: 'bg-emerald-300' },
    { id: 'unicorn', word: 'Unicorn', jp: 'ユニコーン', icon: '🦄', rarity: 4, bg: 'bg-purple-300' },
    { id: 'alien', word: 'Alien', jp: 'うちゅうじん', icon: '👽', rarity: 4, bg: 'bg-green-300' },
    { id: 'crown', word: 'King Crown', jp: 'キング・クラウン', icon: '👑', rarity: 4, bg: 'bg-yellow-400' },
    { id: 'castle', word: 'Castle', jp: 'おしろ', icon: '🏰', rarity: 4, bg: 'bg-stone-300' },
    { id: 'palace', word: 'Palace', jp: 'きゅうでん', icon: '🏛️', rarity: 4, bg: 'bg-yellow-100' },
    { id: 'santa', word: 'Santa', jp: 'サンタ', icon: '🎅', rarity: 4, bg: 'bg-red-300' },
    { id: 'genie', word: 'Genie', jp: 'まじん', icon: '🧞', rarity: 4, bg: 'bg-indigo-300' },
    { id: 'phoenix', word: 'Phoenix', jp: 'フェニックス', icon: '🦅', rarity: 4, bg: 'bg-red-500 text-yellow-100' }, // Eagle icon but style it hot
    { id: 'pegasus', word: 'Pegasus', jp: 'ペガサス', icon: '🐴', rarity: 4, bg: 'bg-sky-300' }, // Horse icon but sky bg
    { id: 'treasure', word: 'Treasure', jp: 'たからばこ', icon: '🏴‍☠️', rarity: 4, bg: 'bg-yellow-500 text-black' }, // Pirate flag as symbol or use Chest? No char for chest... 
    // actually, let's use some specific ones if unicode allows, otherwise re-use
    { id: 'crystal', word: 'Crystal', jp: 'クリスタル', icon: '🔮', rarity: 4, bg: 'bg-purple-400' },
    { id: 'love_letter', word: 'Love Letter', jp: 'ラブレター', icon: '💌', rarity: 4, bg: 'bg-pink-300' },
    { id: 'tophat', word: 'Magic Hat', jp: 'シルクハット', icon: '🎩', rarity: 4, bg: 'bg-black text-white' },
    { id: 'moyai', word: 'Moyai', jp: 'モアイ', icon: '🗿', rarity: 4, bg: 'bg-stone-500 text-white' },
    { id: 'statue', word: 'Statue', jp: 'じゆうのめがみ', icon: '🗽', rarity: 4, bg: 'bg-green-200' },
    { id: 'tokyo', word: 'Tokyo Tower', jp: 'とうきょうタワー', icon: '🗼', rarity: 4, bg: 'bg-red-400' },
    { id: 'shrine', word: 'Shrine', jp: 'とりい', icon: '⛩️', rarity: 4, bg: 'bg-red-300' },
    { id: 'japan', word: 'Japan', jp: 'にほん', icon: '🗾', rarity: 4, bg: 'bg-white' },
    { id: 'world', word: 'The World', jp: 'せかい', icon: '🗺️', rarity: 4, bg: 'bg-blue-300' },
    { id: 'first_sun', word: 'Sunrise', jp: 'ひので', icon: '🌅', rarity: 4, bg: 'bg-orange-300' },
    { id: 'milkyway', word: 'Milky Way', jp: 'あまのがわ', icon: '🌌', rarity: 4, bg: 'bg-indigo-900 text-white' },
];
